import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { useKeepAwake } from 'expo-keep-awake';
import { ScreenContainer } from '@/components/screen-container';
import { useAppState } from '@/lib/app-state';

const yellow = '#F4C400';
const red = '#D72C2C';
const workout = [{ name: 'Supino reto', target: '4 × 10', load: '60 kg', rest: 60 }, { name: 'Crucifixo inclinado', target: '3 × 12', load: '10 kg', rest: 45 }, { name: 'Tríceps corda', target: '4 × 12', load: '25 kg', rest: 45 }];

export default function WorkoutScreen() {
  useKeepAwake();
  const { markWorkoutComplete } = useAppState();
  const [exerciseIndex, setExerciseIndex] = useState(0); const [setIndex, setSetIndex] = useState(0); const [rest, setRest] = useState<number | null>(null); const [paused, setPaused] = useState(false); const [finished, setFinished] = useState(false);
  const current = workout[exerciseIndex]; const totalSets = Number(current.target.split(' ')[0]); const totalProgress = useMemo(() => ((exerciseIndex * 4 + setIndex) / (workout.length * 4)) * 100, [exerciseIndex, setIndex]);
  useEffect(() => { if (rest === null || paused || rest <= 0) return; const interval = setInterval(() => setRest((value) => value === null ? null : value - 1), 1000); return () => clearInterval(interval); }, [rest, paused]);
  useEffect(() => { if (rest === 0) setRest(null); }, [rest]);
  const finishSet = () => { if (setIndex + 1 < totalSets) { setSetIndex((value) => value + 1); setRest(current.rest); return; } if (exerciseIndex + 1 < workout.length) { setExerciseIndex((value) => value + 1); setSetIndex(0); setRest(current.rest); return; } markWorkoutComplete(); setFinished(true); };
  if (finished) return <ScreenContainer edges={['top', 'bottom', 'left', 'right']} className="px-5" containerClassName="bg-background"><View style={styles.finished}><View style={styles.successIcon}><MaterialIcons name="check" size={42} color="#17130A" /></View><Text style={styles.finishedKicker}>SUMMER FIT · TREINO FINALIZADO</Text><Text style={styles.finishedTitle}>Mandou bem!</Text><Text style={styles.finishedText}>Seu treino foi salvo no histórico. Volte amanhã para manter o ritmo.</Text><View style={styles.savedCard}><View><Text style={styles.savedLabel}>DURAÇÃO</Text><Text style={styles.savedValue}>42 min</Text></View><View><Text style={styles.savedLabel}>EXERCÍCIOS</Text><Text style={styles.savedValue}>03</Text></View><View><Text style={styles.savedLabel}>SÉRIES</Text><Text style={styles.savedValue}>11</Text></View></View><Pressable style={styles.primaryButton} onPress={() => router.back()}><Text style={styles.primaryButtonText}>VOLTAR PARA O INÍCIO</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer edges={['top', 'bottom', 'left', 'right']} className="px-5" containerClassName="bg-background"><View style={styles.container}><View style={styles.top}><Pressable style={styles.closeButton} onPress={() => Alert.alert('Sair do treino?', 'Seu progresso atual será mantido apenas nesta sessão.', [{ text: 'Continuar', style: 'cancel' }, { text: 'Sair', style: 'destructive', onPress: () => router.back() }])}><MaterialIcons name="close" size={22} color="#17130A" /></Pressable><View style={styles.topCenter}><Text style={styles.topKicker}>SUMMER FIT</Text><Text style={styles.topTitle}>Treino em andamento</Text></View><Text style={styles.timer}>42:18</Text></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${Math.max(5, totalProgress)}%` }]} /></View><View style={styles.exerciseHeader}><Text style={styles.exerciseKicker}>EXERCÍCIO {exerciseIndex + 1} DE {workout.length}</Text><Text style={styles.exerciseTitle}>{current.name}</Text><Text style={styles.exerciseSub}>{current.target}  ·  carga sugerida {current.load}</Text></View><View style={styles.setCard}><View style={styles.setHeader}><Text style={styles.setLabel}>SÉRIE {setIndex + 1}</Text><Text style={styles.setCount}>{setIndex + 1} / {totalSets}</Text></View><Text style={styles.reps}>{current.target.split(' × ')[1]} <Text style={styles.repsLight}>repetições</Text></Text><View style={styles.loadRow}><MaterialIcons name="fitness-center" size={19} color={red} /><Text style={styles.loadText}>Carga atual</Text><Text style={styles.loadValue}>{current.load}</Text></View></View><View style={styles.setDots}>{Array.from({ length: totalSets }).map((_, index) => <View key={index} style={[styles.setDot, index < setIndex && styles.setDotDone, index === setIndex && styles.setDotCurrent]} />)}</View>{rest !== null ? <View style={styles.restCard}><View style={{ flex: 1 }}><Text style={styles.restKicker}>DESCANSO</Text><Text style={styles.restTimer}>00:{String(rest).padStart(2, '0')}</Text></View><View style={styles.restActions}><Pressable style={styles.restAction} onPress={() => setRest(null)}><Text style={styles.restActionText}>PULAR</Text></Pressable><Pressable style={styles.restAction} onPress={() => setRest(rest + 15)}><Text style={styles.restActionText}>+15s</Text></Pressable><Pressable style={styles.restAction} onPress={() => setPaused((value) => !value)}><Text style={styles.restActionText}>{paused ? 'RETOMAR' : 'PAUSAR'}</Text></Pressable></View></View> : null}<View style={styles.bottom}><Pressable style={({ pressed }) => [styles.primaryButton, pressed && styles.pressed]} onPress={finishSet}><MaterialIcons name="check" size={20} color="#17130A" /><Text style={styles.primaryButtonText}>{setIndex + 1 === totalSets && exerciseIndex + 1 === workout.length ? 'CONCLUIR TREINO' : 'CONCLUIR SÉRIE'}</Text></Pressable><Text style={styles.hint}>Ao concluir, o descanso começa automaticamente.</Text></View></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 17, paddingBottom: 15 },
  top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  closeButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#EADFB9' },
  topCenter: { alignItems: 'center', gap: 2 }, topKicker: { color: red, fontSize: 9, fontWeight: '900', letterSpacing: 1.5 }, topTitle: { color: '#17130A', fontSize: 14, fontWeight: '900' }, timer: { color: red, fontSize: 12, fontWeight: '900' },
  progressTrack: { height: 5, backgroundColor: '#F0E9CE', borderRadius: 8, overflow: 'hidden', marginTop: 26 }, progressFill: { height: 5, backgroundColor: yellow, borderRadius: 8 },
  exerciseHeader: { marginTop: 44, gap: 6 }, exerciseKicker: { color: red, fontSize: 10, fontWeight: '900', letterSpacing: 1.3 }, exerciseTitle: { color: '#17130A', fontSize: 32, fontWeight: '900', letterSpacing: -1 }, exerciseSub: { color: '#756B5C', fontSize: 13 },
  setCard: { backgroundColor: '#FFFFFF', borderRadius: 22, padding: 21, marginTop: 27, borderWidth: 1, borderColor: '#EADFB9' }, setHeader: { flexDirection: 'row', justifyContent: 'space-between' }, setLabel: { color: '#887C6A', fontSize: 11, fontWeight: '900', letterSpacing: 1.2 }, setCount: { color: '#756B5C', fontSize: 12, fontWeight: '800' }, reps: { color: '#17130A', fontSize: 44, fontWeight: '900', marginTop: 18, letterSpacing: -1.4 }, repsLight: { color: '#887C6A', fontSize: 17, fontWeight: '600', letterSpacing: 0 }, loadRow: { flexDirection: 'row', alignItems: 'center', gap: 9, borderTopWidth: 1, borderTopColor: '#F0E8CE', marginTop: 22, paddingTop: 15 }, loadText: { color: '#887C6A', fontSize: 12, flex: 1 }, loadValue: { color: '#17130A', fontSize: 15, fontWeight: '900' },
  setDots: { flexDirection: 'row', gap: 7, justifyContent: 'center', marginTop: 17 }, setDot: { width: 36, height: 6, borderRadius: 5, backgroundColor: '#EADFB9' }, setDotDone: { backgroundColor: '#3B9845' }, setDotCurrent: { backgroundColor: yellow },
  restCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF4C2', borderRadius: 18, padding: 15, marginTop: 20, borderWidth: 1, borderColor: '#F0D76E' }, restKicker: { color: '#856900', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 }, restTimer: { color: red, fontSize: 26, fontWeight: '900', marginTop: 3 }, restActions: { flexDirection: 'row', gap: 7 }, restAction: { paddingHorizontal: 8, paddingVertical: 8, borderRadius: 9, backgroundColor: '#FFE99A' }, restActionText: { color: '#66541A', fontSize: 9, fontWeight: '900' }, bottom: { marginTop: 'auto', gap: 10 }, primaryButton: { height: 56, backgroundColor: yellow, borderRadius: 16, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, primaryButtonText: { color: '#17130A', fontSize: 12, fontWeight: '900', letterSpacing: 0.9 }, hint: { color: '#958A76', fontSize: 11, textAlign: 'center' }, pressed: { opacity: 0.8, transform: [{ scale: 0.99 }] },
  finished: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingBottom: 30 }, successIcon: { width: 82, height: 82, borderRadius: 30, backgroundColor: yellow, alignItems: 'center', justifyContent: 'center', marginBottom: 27 }, finishedKicker: { color: red, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, finishedTitle: { color: '#17130A', fontSize: 32, fontWeight: '900', marginTop: 8 }, finishedText: { color: '#756B5C', fontSize: 14, textAlign: 'center', lineHeight: 21, marginTop: 13, maxWidth: 310 }, savedCard: { flexDirection: 'row', justifyContent: 'space-around', width: '100%', paddingVertical: 19, backgroundColor: '#FFFFFF', borderRadius: 18, borderWidth: 1, borderColor: '#EADFB9', marginTop: 26, marginBottom: 24 }, savedLabel: { color: '#887C6A', fontSize: 9, fontWeight: '900', letterSpacing: 1 }, savedValue: { color: '#17130A', fontSize: 20, fontWeight: '900', marginTop: 5 },
});
